version: '3.8'
services:
        nginx:
                container_name: web
                image: nginx:1.17.8
                volumes:
                    - ${PWD}/nginx:/etc/nginx
                restart: on-failure
                ports:
                    - "8000:80"
                stop_grace_period: 30s
                depends_on: [ backend ]
                networks:
                    net:
                        ipv4_address: 10.254.1.2
        backend:
                image: ${BACKENDIMAGE}
                environment:
                        HOME: /data
                container_name: backend
                volumes:
                        - ${PWD}/backend:/data/
                restart: on-failure
                stop_grace_period: 30s
                networks:
                    net:
                        ipv4_address: 10.254.1.4

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 10.254.1.0/24
